### ISSUE TITLE
selector is getting all commonLabels 

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-application#13]
It looks like kustomize is adding all commonLabels to the pod selector of the service, but not to the service. 

https://github.com/thoth-station/thoth-application/blob/419938291948d4f0ca8bcde2350517a2dcae1e8f/core/overlays/test/postgresql-ephemeral.yaml#L24-L25

if is:
```
  selector:
    app.kubernetes.io/component: core
    app.kubernetes.io/managed-by: kustomize-ksops
    app.kubernetes.io/name: thoth
    app.kubernetes.io/version: '0.6'
    service: pgbouncer
```

but should be
```
  selector:
    service: pgbouncer
```

@HumairAK @harshad16
