### ISSUE TITLE
Prow job pods can not be created

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#1332]
**Describe the bug**
Prow job pods can not be created due to resource limits and requests mismatch.
```
Pod can not be created: Pod "3ae2adf9-b73e- ... must be less than or eq
```
![resources](https://user-images.githubusercontent.com/14028058/118547353-370ae300-b727-11eb-8787-cb9c93c02c34.png)

As the quota limits are set on the prow namespace, it would require pods with resource requests to obey the limits.

**Comment by harshad16** [comment]
Solutions:
[x] . Remove the resource requests from the prow jobs, so that they directly take the default limits i.e
```
    - resources:
        limits:
          cpu: 500m
          memory: 1000Mi
        requests:
          cpu: 300m
          memory: 400Mi
```

[ ]. Add both `requests` and `limits` while setting up prow jobs individually.
