### ISSUE TITLE
TypeError: 'SolvedPackageMessage' object is not callable

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#214]
**Describe the bug**
Send Kafka message task fails in Argo workflow.

**To Reproduce**
1. Create Argo Workflow called `test-send-message.yaml`:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: "test-send-message-"
  labels:
    app: thoth
    template: test-send-message
    component: test-send-message
spec:
  serviceAccountName: argo
  entrypoint: send-message

  volumes:
    - name: workdir
      emptyDir: {}
    - name: output
      emptyDir: {}
    - name: kafka-secrets
      secret:
        secretName: "kafka"
        items:
          - key: kafka_ca.crt
            path: kafka_ca.crt

  templates:
    - name: "send-message"
      archiveLocation:
        archiveLogs: false
      dag:
        tasks:
          - name: "send-message"
            templateRef:
              name: "send-message"
              template: "send-message"
            arguments:
              parameters:
                - name: THOTH_MESSAGING_TOPIC_NAME
                  value: "thoth.solver.solved-package"
                - name: THOTH_MESSAGING_CREATE_IF_NOT_EXIST
                  value: "1"
                - name: THOTH_MESSAGING_MESSAGE_CONTENTS
                  value: '{"package_name": {"type": "str", "value": "tensorflow"}, "package_version": {"type": "str", "value": "2.2.0"}, "index_url": {"type": "str", "value": "https://pypi.org/simple"}, "solver": {"type": "str", "value": "solver-rhel-8-py36"}}'

```

2. login in ocp cluster in thoth-test-core
3. Run `argo submit test-send-message.yaml`

**Expected behavior**
The message is sent successfully.

**Screenshots**
```
test-send-message-n2zcg-1364865353: [2020-08-06 08:41:13,756] [22] [ERROR] [^Worker]: Error: TypeError("'SolvedPackageMessage' object is not callable",) 
test-send-message-n2zcg-1364865353: Traceback (most recent call last):
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/worker.py", line 273, in execute_from_commandline
test-send-message-n2zcg-1364865353:     self.loop.run_until_complete(self._starting_fut)
test-send-message-n2zcg-1364865353:   File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
test-send-message-n2zcg-1364865353:     return future.result()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
test-send-message-n2zcg-1364865353:     await self._default_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
test-send-message-n2zcg-1364865353:     await self._actually_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
test-send-message-n2zcg-1364865353:     await child.maybe_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
test-send-message-n2zcg-1364865353:     await self.start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
test-send-message-n2zcg-1364865353:     await self._default_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
test-send-message-n2zcg-1364865353:     await self._actually_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 760, in _actually_start
test-send-message-n2zcg-1364865353:     await self.on_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 1073, in on_start
test-send-message-n2zcg-1364865353:     await self._fut
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 598, in execute
test-send-message-n2zcg-1364865353:     await self.run(*args, **kwargs)
test-send-message-n2zcg-1364865353:   File "/opt/app-root/src/cli.py", line 99, in messaging
test-send-message-n2zcg-1364865353:     topic_retention_time_second=topic_retention_time,
test-send-message-n2zcg-1364865353: TypeError: 'SolvedPackageMessage' object is not callable
test-send-message-n2zcg-1364865353:     await asyncio.shield(child.stop())
test-send-message-n2zcg-1364865353: Traceback (most recent call last):
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 863, in _default_stop_children
test-send-message-n2zcg-1364865353: [2020-08-06 08:41:13,767] [22] [ERROR] [^Worker]: Error while stopping child <messaging: stopping >: TypeError("'SolvedPackageMessage' object is not callable",) 
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 839, in stop
test-send-message-n2zcg-1364865353:     await self.on_stop()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 1084, in on_stop
test-send-message-n2zcg-1364865353:     fut.result()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/worker.py", line 273, in execute_from_commandline
test-send-message-n2zcg-1364865353:     self.loop.run_until_complete(self._starting_fut)
test-send-message-n2zcg-1364865353:   File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
test-send-message-n2zcg-1364865353:     return future.result()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
test-send-message-n2zcg-1364865353:     await self._default_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
test-send-message-n2zcg-1364865353:     await self._actually_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
test-send-message-n2zcg-1364865353:     await child.maybe_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
test-send-message-n2zcg-1364865353:     await self.start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
test-send-message-n2zcg-1364865353:     await self._default_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
test-send-message-n2zcg-1364865353:     await self._actually_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 760, in _actually_start
test-send-message-n2zcg-1364865353:     await self.on_start()
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 1073, in on_start
test-send-message-n2zcg-1364865353:     await self._fut
test-send-message-n2zcg-1364865353:   File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 598, in execute
test-send-message-n2zcg-1364865353:     await self.run(*args, **kwargs)
test-send-message-n2zcg-1364865353:   File "/opt/app-root/src/cli.py", line 99, in messaging
test-send-message-n2zcg-1364865353:     topic_retention_time_second=topic_retention_time,
test-send-message-n2zcg-1364865353: TypeError: 'SolvedPackageMessage' object is not callable
```

**Additional context**
This task will be included in different Argo workflows.

**Comment by harshad16** [comment]
the topic name is changed. maybe this pr https://github.com/thoth-station/thoth-application/pull/209 would have fixed this issue.

**Comment by pacospace** [comment]
> the topic name is changed. maybe this pr #209 would have fixed this issue.

Thanks @harshad16! I actually tested with that change and I received that error:

```
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: "test-send-message-"
  labels:
    app: thoth
    template: test-send-message
    component: test-send-message
spec:
  serviceAccountName: argo
  entrypoint: send-message

  volumes:
    - name: workdir
      emptyDir: {}
    - name: output
      emptyDir: {}
    - name: kafka-secrets
      secret:
        secretName: "kafka"
        items:
          - key: kafka_ca.crt
            path: kafka_ca.crt

  templates:
    - name: "send-message"
      archiveLocation:
        archiveLogs: false
      dag:
        tasks:
          - name: "send-message"
            templateRef:
              name: "send-message"
              template: "send-message"
            arguments:
              parameters:
                - name: THOTH_MESSAGING_TOPIC_NAME
                  value: "thoth.solver.solved-package"
                - name: THOTH_MESSAGING_CREATE_IF_NOT_EXIST
                  value: "1"
                - name: THOTH_MESSAGING_MESSAGE_CONTENTS
                  value: '{"package_name": {"type": "str", "value": "tensorflow"}, "package_version": {"type": "str", "value": "2.2.0"}, "index_url": {"type": "str", "value": "https://pypi.org/simple"}, "solver": {"type": "str", "value": "solver-rhel-8-py36"}}'
```
