### ISSUE TITLE
thoth.solver.solved-package is not available during auto-create initialization 

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thoth-application#231]
**Describe the bug**
Send Kafka message task fails in Argo workflow.

**To Reproduce**
1. Create Argo Workflow called `test-send-message.yaml`:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: "test-send-message-"
  labels:
    app: thoth
    template: test-send-message
    component: test-send-message
spec:
  serviceAccountName: argo
  entrypoint: send-message

  volumes:
    - name: workdir
      emptyDir: {}
    - name: output
      emptyDir: {}
    - name: kafka-secrets
      secret:
        secretName: "kafka"
        items:
          - key: kafka_ca.crt
            path: kafka_ca.crt

  templates:
    - name: "send-message"
      archiveLocation:
        archiveLogs: false
      dag:
        tasks:
          - name: "send-message"
            templateRef:
              name: "send-message"
              template: "send-message"
            arguments:
              parameters:
                - name: THOTH_MESSAGING_TOPIC_NAME
                  value: "thoth.solver.solved-package"
                - name: THOTH_MESSAGING_CREATE_IF_NOT_EXIST
                  value: "1"
                - name: THOTH_MESSAGING_MESSAGE_CONTENTS
                  value: '{"package_name": {"type": "str", "value": "tensorflow"}, "package_version": {"type": "str", "value": "2.2.0"}, "index_url": {"type": "str", "value": "https://pypi.org/simple"}, "solver": {"type": "str", "value": "solver-rhel-8-py36"}}'

```

2. login in ocp cluster in thoth-test-core
3. Run `argo submit test-send-message.yaml`

**Expected behavior**
The message is sent successfully.

**Screenshots**
```
[2020-08-10 07:55:16,626] [22] [WARNING] Got error produce response on topic-partition TopicPartition(topic='thoth.solver.solved-package', partition=0), retrying. Error: <class 'kafka.errors.UnknownTopicOrPartitionError'> 
[2020-08-10 07:55:16,629] [22] [WARNING] Topic thoth.solver.solved-package is not available during auto-create initialization 
```

**Additional context**
This task will be included in different Argo workflows.
