### ISSUE TITLE
Integration test for prod cluster is stuck at CreateContainerConfigError

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-application#2593]
**Describe the bug**
The integration tests for the prod cluster are not in a running state, it has been failing due to the CreateContainerConfigError.
The application is looking for config map `thoth` in the repository and can't find it.

![Screenshot from 2022-06-20 11-45-49](https://user-images.githubusercontent.com/14028058/174638340-0595055a-15b9-4bc0-b54e-e4f19525b698.png)
```
  containerStatuses:
    - name: integration-tests
      state:
        waiting:
          reason: CreateContainerConfigError
          message: configmap "thoth" not found
```
