### ISSUE TITLE
Add TTLStrategy to all workflows

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/thoth-application#302]
**Is your feature request related to a problem? Please describe.**
Workflows are never deleted unless someone manually goes through and runs:
`$ argo delete --all`
or
`$ argo delete --completed`
This will cause the WorkflowController to constantly increase in memory usage.

**Describe the solution you'd like**
Add a TTLStrategy as seen [here](https://github.com/argoproj/argo/blob/master/examples/gc-ttl.yaml) to automatically delete workflows after a certain amount of time.  We may want to also archive workflow logs so that we don't lose the ability to debug.

**Describe alternatives you've considered**
* add some job which runs periodically and deletes workflows
* continue deleting manually
* only create TTL strategy for succeeded workflows so that we can debug failed or errored workflows

**Comment by pacospace** [comment]
I think all workflows except SI have that set:
```
      ttlStrategy:
        secondsAfterSuccess: 7200
        secondsAfterFailure: 7200
```

except for solver which has:
```
      # kill workflow if running too much time
      activeDeadlineSeconds: 2600
      podGC:
        strategy: OnWorkflowSuccess
      ttlStrategy:
        secondsAfterSuccess: 1200
        secondsAfterFailure: 1200
```
